tap "adoptopenjdk/openjdk"
tap "chef/chef"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "cask"
brew "cocoapods"
brew "coreutils"
brew "direnv"
brew "git"
brew "gnupg"
brew "go"
brew "htop"
brew "jenv"
brew "jq"
brew "libtool"
brew "mas"
brew "maven"
brew "newt"
brew "nmap"
brew "nvm"
brew "pyenv"
brew "telnet"
brew "tree"
brew "watch"
brew "wget"
brew "zlib"
cask "adoptopenjdk11"
cask "adoptopenjdk13"
cask "adoptopenjdk14"
cask "adoptopenjdk8"
cask "appcleaner"
cask "authy"
cask "blackhole"
cask "chef-workstation"
cask "firefox"
cask "flux"
cask "gimp"
cask "grandperspective"
cask "haptickey"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "nightowl"
cask "postman"
cask "shortcuts"
cask "sizeup"
cask "smcfancontrol"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "Download Shuttle", id: 847809913
mas "Kindle", id: 405399194
mas "OneDrive", id: 823766827
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Trello", id: 1278508951
mas "Twitter", id: 409789998
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
